VirtoCommerce/vc-module-customer-review

- src/VirtoCommerce.CustomerReviews.Web/Scripts/VirtoCommerce.CustomerReviews.js
VP-2126 Don't show widget if a user hasn't permission
> VP-2126 Don't show widget if user hasn't permission

- src/VirtoCommerce.CustomerReviews.Data/Services/CustomerReviewService.cs
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
> VP-5334: Call ClearCache before publish event

- src/VirtoCommerce.CustomerReviews.Web/Scripts/blades/reviews-list.js
> VP-6864: Fix header icon

- src/VirtoCommerce.CustomerReviews.Core/Models/ReviewStatusChangeData.cs
- src/VirtoCommerce.CustomerReviews.Data/Services/CustomerReviewService.cs
Jira: https://virtocommerce.atlassian.net/browse/VP-7269
> VP-7269: Fix ReviewStatus Changed Event is empty for WebHook

- src/VirtoCommerce.CustomerReviews.Core/VirtoCommerce.CustomerReviews.Core.csproj
- src/VirtoCommerce.CustomerReviews.Data/VirtoCommerce.CustomerReviews.Data.csproj
https://virtocommerce.atlassian.net/browse/PT-207
> PT-207: Enable Source link support

- .github/workflows/publish_nugets.yml
https://virtocommerce.atlassian.net/browse/PT-6201
> Add "publish_nugets" manifest

- .github/workflows/publish_nugets.yml
> Remove comments

- .github/workflows/publish_nugets.yml
> Add "on repository_dispatch" trigger

- .github/workflows/main.yml
- Directory.Build.props
- src/VirtoCommerce.CustomerReviews.Core/VirtoCommerce.CustomerReviews.Core.csproj
- src/VirtoCommerce.CustomerReviews.Data/VirtoCommerce.CustomerReviews.Data.csproj
- src/VirtoCommerce.CustomerReviews.Web/VirtoCommerce.CustomerReviews.Web.csproj
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
- tests/VirtoCommerce.CustomerReviews.Test/VirtoCommerce.CustomerReviews.Test.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
> PT-1956: Bump .Net and EF up to 6

- src/VirtoCommerce.CustomerReviews.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-7292
> PT-7292: Remove redundant BuildServiceProvider from the module startup

- src/VirtoCommerce.CustomerReviews.Data/Repositories/CustomerReviewsDbContext.cs
Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152
> PT-9152: Fix EF validation runtime warnings

- src/VirtoCommerce.CustomerReviews.Web/Module.cs
> Fix sonar errors

- src/VirtoCommerce.CustomerReviews.Web/Localizations/en.customerReviews.json
- src/VirtoCommerce.CustomerReviews.Web/Scripts/widgets/product-rating-widget.tpl.html
fix: Wrong localization in review widget
https://virtocommerce.atlassian.net/browse/PT-10380
> PT-10380: Wrong localization in review widget

- src/VirtoCommerce.CustomerReviews.Web/package-lock.json
- src/VirtoCommerce.CustomerReviews.Web/package.json
- src/VirtoCommerce.CustomerReviews.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
> PT-9395: add nodejs-lts support

- .editorconfig
- Directory.Build.props
- VirtoCommerce.CustomerReviews.sln.DotSettings
- src/VirtoCommerce.CustomerReviews.Core/Services/ICustomerReviewSearchService.cs
- src/VirtoCommerce.CustomerReviews.Core/Services/ICustomerReviewService.cs
- src/VirtoCommerce.CustomerReviews.Core/VirtoCommerce.CustomerReviews.Core.csproj
- src/VirtoCommerce.CustomerReviews.Data.MySql/VirtoCommerce.CustomerReviews.Data.MySql.csproj
- src/VirtoCommerce.CustomerReviews.Data.PostgreSql/VirtoCommerce.CustomerReviews.Data.PostgreSql.csproj
- src/VirtoCommerce.CustomerReviews.Data.SqlServer/VirtoCommerce.CustomerReviews.Data.SqlServer.csproj
- src/VirtoCommerce.CustomerReviews.Data/BackgroundJobs/RequestCustomerReviewJob.cs
- src/VirtoCommerce.CustomerReviews.Data/Handlers/OrderChangedEventHandler.cs
- src/VirtoCommerce.CustomerReviews.Data/Repositories/CustomerReviewRepository.cs
- src/VirtoCommerce.CustomerReviews.Data/Repositories/ICustomerReviewRepository.cs
- src/VirtoCommerce.CustomerReviews.Data/Services/CustomerReviewSearchService.cs
- src/VirtoCommerce.CustomerReviews.Data/Services/CustomerReviewService.cs
- src/VirtoCommerce.CustomerReviews.Data/Services/RatingService.cs
- src/VirtoCommerce.CustomerReviews.Data/VirtoCommerce.CustomerReviews.Data.csproj
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Authorization/CustomerReviewAuthorizationHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Commands/CreateCustomerReviewCommandHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Queries/CustomerReviewsQueryHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/VirtoCommerce.CustomerReviews.ExperienceApi.csproj
- src/VirtoCommerce.CustomerReviews.Web/Controllers/Api/CustomerReviewsModuleController.cs
- src/VirtoCommerce.CustomerReviews.Web/Module.cs
- src/VirtoCommerce.CustomerReviews.Web/VirtoCommerce.CustomerReviews.Web.csproj
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
- tests/VirtoCommerce.CustomerReviews.Test/CustomerReviewsTests.cs
- tests/VirtoCommerce.CustomerReviews.Test/TestData/customerReviews.json
- tests/VirtoCommerce.CustomerReviews.Test/VirtoCommerce.CustomerReviews.Test.csproj
https://virtocommerce.atlassian.net/browse/PT-10449
> PT-10449: Update Crud and Search services

- src/VirtoCommerce.CustomerReviews.Core/VirtoCommerce.CustomerReviews.Core.csproj
- src/VirtoCommerce.CustomerReviews.Data/Repositories/CustomerReviewsDbContext.cs
- src/VirtoCommerce.CustomerReviews.Data/Services/RatingService.cs
- src/VirtoCommerce.CustomerReviews.Data/VirtoCommerce.CustomerReviews.Data.csproj
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
fix: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified
https://virtocommerce.atlassian.net/browse/PT-13500
> PT-13500: Fix DateTimeKind of Unspecified

- Directory.Build.props
- src/VirtoCommerce.CustomerReviews.Core/VirtoCommerce.CustomerReviews.Core.csproj
- src/VirtoCommerce.CustomerReviews.Data.MySql/VirtoCommerce.CustomerReviews.Data.MySql.csproj
- src/VirtoCommerce.CustomerReviews.Data.PostgreSql/VirtoCommerce.CustomerReviews.Data.PostgreSql.csproj
- src/VirtoCommerce.CustomerReviews.Data.SqlServer/VirtoCommerce.CustomerReviews.Data.SqlServer.csproj
- src/VirtoCommerce.CustomerReviews.Data/VirtoCommerce.CustomerReviews.Data.csproj
- src/VirtoCommerce.CustomerReviews.ExperienceApi/VirtoCommerce.CustomerReviews.ExperienceApi.csproj
- src/VirtoCommerce.CustomerReviews.Web/VirtoCommerce.CustomerReviews.Web.csproj
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
- src/VirtoCommerce.CustomerReviews.Web/package-lock.json
- tests/VirtoCommerce.CustomerReviews.Test/VirtoCommerce.CustomerReviews.Test.csproj
feat: Update to net8
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerReviews_3.800.0-pr-57-0915.zip
> PT-14740: Update to net8

- src/VirtoCommerce.CustomerReviews.Web/Scripts/blades/reviews-list.tpl.html
feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerReviews_3.802.0-pr-59-14f4.zip
> VCST-972: Remove Counter from Search panel

- module.ignore
- src/VirtoCommerce.CustomerReviews.Core/VirtoCommerce.CustomerReviews.Core.csproj
- src/VirtoCommerce.CustomerReviews.Data.MySql/VirtoCommerce.CustomerReviews.Data.MySql.csproj
- src/VirtoCommerce.CustomerReviews.Data.PostgreSql/VirtoCommerce.CustomerReviews.Data.PostgreSql.csproj
- src/VirtoCommerce.CustomerReviews.Data.SqlServer/VirtoCommerce.CustomerReviews.Data.SqlServer.csproj
- src/VirtoCommerce.CustomerReviews.Data/VirtoCommerce.CustomerReviews.Data.csproj
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Authorization/CustomerReviewAuthorizationHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Commands/CreateCustomerReviewCommand.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Commands/CreateCustomerReviewCommandBuilder.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Mapping/RatingProfile.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Middleware/EvalProductVendorRatingMiddleware.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Queries/CustomerReviewQueryBuilder.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Queries/CustomerReviewsQuery.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Queries/CustomerReviewsQueryHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Schemas/CustomerReviewType.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/VirtoCommerce.CustomerReviews.ExperienceApi.csproj
- src/VirtoCommerce.CustomerReviews.Web/Module.cs
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1352
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerReviews_3.804.0-pr-61-a17d.zip
> VCST-1352: update to Xapi module

- src/VirtoCommerce.CustomerReviews.ExperienceApi/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/VirtoCommerce.CustomerReviews.ExperienceApi.csproj
- src/VirtoCommerce.CustomerReviews.Web/Module.cs
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
/ui/playground/customerReviews
https://virtocommerce.atlassian.net/browse/VCST-2241
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerReviews_3.809.0-pr-66-5c71.zip
> VCST-2241: add scoped schema

- src/VirtoCommerce.CustomerReviews.ExperienceApi/Authorization/CustomerReviewAuthorizationHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Commands/CreateCustomerReviewCommand.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Commands/CreateCustomerReviewCommandBuilder.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Commands/CreateCustomerReviewCommandHandler.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Mapping/RatingProfile.cs
- src/VirtoCommerce.CustomerReviews.ExperienceApi/Schemas/CreateCustomerReviewCommandType.cs
feat: Mutation CreateCustomerReview is deprecated
https://virtocommerce.atlassian.net/browse/VCST-2562
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerReviews_3.901.0-pr-71-cb42.zip
> VCST-2562: Mutation CreateCustomerReview is deprecated

- src/VirtoCommerce.CustomerReviews.ExperienceApi/VirtoCommerce.CustomerReviews.ExperienceApi.csproj
- src/VirtoCommerce.CustomerReviews.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2589
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CustomerReviews_3.902.0-pr-73-a0b0.zip
> VCST-2589: update Xapi dependency (Mediatr)
